# This is a basic workflow to help you get started with Actions

name: Dry Run

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  importtest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #fills up dummy files
      - name: create dummy files
        run: |
          echo "nope">PREFIX.txt
          echo "nopenopenope">.token.txt

      
      #installs pip modules
      - name: "Install modules"
        run: pip3 install discord.py scikit-image scipy requests
      # checks if program can run
      - name: "test-run"
        run: python3.8 bot.py debug


