name: Code Style

# Controls when the action will run.
on: push
run-name: "Code Style"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  flake8:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9.5"
      - name: setup
        run: |
          cd src
          pip install -r ../requirements.txt
      - name: "run"
        run: flake8
  isort:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9.5"
      - name: setup
        run: |
          cd src
          pip install -r ../requirements.txt
      - name: "run"
        run: isort --check .
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9.5"
      - name: setup
        run: |
          cd src
          pip install -r ../requirements.txt
      - name: "run"
        run: black --check .
