name: Code Style

# Controls when the action will run.
on: push
run-name: "Code Style"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  flake8:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9.5"

      #prepares everything
      - name: setup
        run: |
          cd src
          pip install -r ../requirements.txt

        # checks if program can run
      - name: "run"
        run: |
          cd src
          flake8
